const games = [
  {
    id: "elden-ring",
    title: "Elden Ring",
    titleKo: "엘든 링",
    genre: "Action RPG",
    tags: ["오픈월드", "소울라이크", "탐험", "판타지"],
    mood: ["도전적", "몰입감"],
    description: "광활한 세계와 높은 난이도 전투가 특징인 액션 RPG"
  },
  {
    id: "dark-souls-3",
    title: "Dark Souls III",
    titleKo: "다크 소울 3",
    genre: "Action RPG",
    tags: ["소울라이크", "보스전", "다크판타지", "전투"],
    mood: ["도전적", "긴장감"],
    description: "정교한 전투와 강한 성취감을 주는 다크 판타지 액션 RPG"
  },
  {
    id: "the-witcher-3",
    title: "The Witcher 3: Wild Hunt",
    titleKo: "더 위쳐 3: 와일드 헌트",
    genre: "RPG",
    tags: ["오픈월드", "스토리", "판타지", "선택"],
    mood: ["몰입감", "서사적"],
    description: "풍부한 이야기와 선택 중심 퀘스트가 돋보이는 오픈월드 RPG"
  },
  {
    id: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    titleKo: "발더스 게이트 3",
    genre: "RPG",
    tags: ["턴제", "스토리", "파티", "선택"],
    mood: ["전략적", "서사적"],
    description: "선택과 주사위 판정, 파티 전투가 결합된 깊이 있는 RPG"
  },
  {
    id: "stardew-valley",
    title: "Stardew Valley",
    titleKo: "스타듀 밸리",
    genre: "Simulation",
    tags: ["농장", "생활", "제작", "관계"],
    mood: ["편안함", "따뜻함"],
    description: "농장 운영과 마을 생활을 느긋하게 즐길 수 있는 생활 시뮬레이션"
  },
  {
    id: "animal-crossing",
    title: "Animal Crossing: New Horizons",
    titleKo: "모여봐요 동물의 숲",
    genre: "Simulation",
    tags: ["생활", "꾸미기", "수집", "섬"],
    mood: ["편안함", "따뜻함"],
    description: "섬을 꾸미고 이웃과 교류하는 느긋한 생활형 게임"
  },
  {
    id: "minecraft",
    title: "Minecraft",
    titleKo: "마인크래프트",
    genre: "Sandbox",
    tags: ["생존", "건축", "제작", "탐험"],
    mood: ["창의적", "자유로움"],
    description: "블록 세계에서 건축, 탐험, 생존을 자유롭게 즐기는 샌드박스 게임"
  },
  {
    id: "terraria",
    title: "Terraria",
    titleKo: "테라리아",
    genre: "Sandbox",
    tags: ["생존", "제작", "탐험", "보스전"],
    mood: ["자유로움", "모험적"],
    description: "2D 세계에서 자원을 모으고 강력한 보스를 상대하는 샌드박스 어드벤처"
  },
  {
    id: "hades",
    title: "Hades",
    titleKo: "하데스",
    genre: "Roguelike",
    tags: ["액션", "로그라이크", "스토리", "신화"],
    mood: ["빠른", "도전적"],
    description: "빠른 전투와 반복 플레이 속 이야기 전개가 강점인 로그라이크 액션 게임"
  },
  {
    id: "dead-cells",
    title: "Dead Cells",
    titleKo: "데드 셀",
    genre: "Roguelike",
    tags: ["액션", "로그라이크", "플랫포머", "전투"],
    mood: ["빠른", "도전적"],
    description: "속도감 있는 전투와 반복 도전이 핵심인 로그라이크 액션 플랫포머"
  },
  {
    id: "civilization-vi",
    title: "Sid Meier's Civilization VI",
    titleKo: "시드 마이어의 문명 VI",
    genre: "Strategy",
    tags: ["턴제", "문명", "전략", "확장"],
    mood: ["전략적", "집중"],
    description: "문명을 성장시키며 외교, 과학, 전쟁을 운영하는 턴제 전략 게임"
  },
  {
    id: "xcom-2",
    title: "XCOM 2",
    titleKo: "엑스컴 2",
    genre: "Strategy",
    tags: ["턴제", "전술", "분대", "SF"],
    mood: ["전략적", "긴장감"],
    description: "분대 단위 전술과 자원 관리가 결합된 턴제 전략 게임"
  },
  {
    id: "portal-2",
    title: "Portal 2",
    titleKo: "포털 2",
    genre: "Puzzle",
    tags: ["퍼즐", "물리", "스토리", "협동"],
    mood: ["영리함", "유쾌함"],
    description: "포털 장치를 이용해 공간 퍼즐을 해결하는 퍼즐 어드벤처 게임"
  },
  {
    id: "the-witness",
    title: "The Witness",
    titleKo: "더 위트니스",
    genre: "Puzzle",
    tags: ["퍼즐", "탐험", "섬", "관찰"],
    mood: ["차분함", "영리함"],
    description: "섬 곳곳의 규칙을 관찰하며 퍼즐을 풀어가는 탐험형 퍼즐 게임"
  },
  {
    id: "hollow-knight",
    title: "Hollow Knight",
    titleKo: "할로우 나이트",
    genre: "Metroidvania",
    tags: ["탐험", "플랫포머", "보스전", "다크판타지"],
    mood: ["몰입감", "도전적"],
    description: "거대한 지하 왕국을 탐험하고 강력한 적과 싸우는 메트로배니아 게임"
  },
  {
    id: "ori-will-of-the-wisps",
    title: "Ori and the Will of the Wisps",
    titleKo: "오리와 도깨비불",
    genre: "Metroidvania",
    tags: ["탐험", "플랫포머", "감성", "판타지"],
    mood: ["감성적", "아름다움"],
    description: "부드러운 움직임과 감성적인 연출이 돋보이는 액션 플랫포머"
  },
  {
    id: "celeste",
    title: "Celeste",
    titleKo: "셀레스트",
    genre: "Platformer",
    tags: ["플랫포머", "정밀조작", "스토리", "도전"],
    mood: ["도전적", "감성적"],
    description: "정밀한 조작과 성장 이야기를 함께 담은 고난도 플랫포머"
  },
  {
    id: "slay-the-spire",
    title: "Slay the Spire",
    titleKo: "슬레이 더 스파이어",
    genre: "Card Strategy",
    tags: ["카드", "로그라이크", "전략", "덱빌딩"],
    mood: ["전략적", "집중"],
    description: "카드를 선택하고 덱을 발전시키며 탑을 오르는 전략 로그라이크"
  },
  {
    id: "subnautica",
    title: "Subnautica",
    titleKo: "서브노티카",
    genre: "Survival",
    tags: ["생존", "탐험", "제작", "해양"],
    mood: ["몰입감", "긴장감"],
    description: "낯선 해양 행성에서 자원을 모으고 생존하는 탐험형 생존 게임"
  },
  {
    id: "dont-starve",
    title: "Don't Starve",
    titleKo: "돈 스타브",
    genre: "Survival",
    tags: ["생존", "제작", "로그라이크", "자원관리"],
    mood: ["긴장감", "기묘함"],
    description: "독특한 세계에서 굶주림과 위험을 관리하는 생존 게임"
  },
  {
    id: "mass-effect-2",
    title: "Mass Effect 2",
    titleKo: "매스 이펙트 2",
    genre: "RPG",
    tags: ["SF", "스토리", "파티", "선택"],
    mood: ["서사적", "몰입감"],
    description: "동료와 선택, 우주 서사가 중심인 SF RPG"
  },
  {
    id: "it-takes-two",
    title: "It Takes Two",
    titleKo: "잇 테이크 투",
    genre: "Co-op Adventure",
    tags: ["협동", "퍼즐", "플랫포머", "스토리"],
    mood: ["유쾌함", "창의적"],
    description: "두 명이 함께 다양한 장치를 해결하는 협동 어드벤처 게임"
  },
  {
    id: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    titleKo: "사이버펑크 2077",
    genre: "RPG",
    tags: ["오픈월드", "SF", "스토리", "선택"],
    mood: ["몰입감", "긴장감"],
    description: "거대한 미래 도시와 선택 중심 서사가 결합된 오픈월드 RPG"
  },
  {
    id: "red-dead-redemption-2",
    title: "Red Dead Redemption 2",
    titleKo: "레드 데드 리뎀션 2",
    genre: "Open World",
    tags: ["오픈월드", "스토리", "탐험", "서부"],
    mood: ["몰입감", "서사적"],
    description: "방대한 서부 세계와 인물 서사가 돋보이는 오픈월드 어드벤처"
  },
  {
    id: "god-of-war",
    title: "God of War",
    titleKo: "갓 오브 워",
    genre: "Action Adventure",
    tags: ["액션", "스토리", "신화", "전투"],
    mood: ["서사적", "몰입감"],
    description: "강렬한 전투와 부자 관계 서사가 중심인 액션 어드벤처"
  },
  {
    id: "horizon-zero-dawn",
    title: "Horizon Zero Dawn",
    titleKo: "호라이즌 제로 던",
    genre: "Action RPG",
    tags: ["오픈월드", "탐험", "SF", "전투"],
    mood: ["모험적", "몰입감"],
    description: "기계 생명체가 지배하는 세계를 탐험하는 오픈월드 액션 RPG"
  },
  {
    id: "ghost-of-tsushima",
    title: "Ghost of Tsushima",
    titleKo: "고스트 오브 쓰시마",
    genre: "Action Adventure",
    tags: ["오픈월드", "전투", "스토리", "잠입"],
    mood: ["서사적", "몰입감"],
    description: "아름다운 섬과 검술 전투가 어우러진 사무라이 액션 어드벤처"
  },
  {
    id: "monster-hunter-world",
    title: "Monster Hunter: World",
    titleKo: "몬스터 헌터: 월드",
    genre: "Action RPG",
    tags: ["액션", "협동", "전투", "제작"],
    mood: ["도전적", "모험적"],
    description: "거대 몬스터 사냥과 장비 제작이 핵심인 협동 액션 RPG"
  },
  {
    id: "sekiro",
    title: "Sekiro: Shadows Die Twice",
    titleKo: "세키로: 섀도우 다이 트와이스",
    genre: "Action Adventure",
    tags: ["소울라이크", "전투", "잠입", "보스전"],
    mood: ["도전적", "긴장감"],
    description: "정밀한 검술과 패링 중심 전투가 특징인 고난도 액션 어드벤처"
  },
  {
    id: "bloodborne",
    title: "Bloodborne",
    titleKo: "블러드본",
    genre: "Action RPG",
    tags: ["소울라이크", "보스전", "다크판타지", "전투"],
    mood: ["도전적", "기묘함"],
    description: "고딕 공포 분위기와 공격적인 전투가 강점인 액션 RPG"
  },
  {
    id: "nioh-2",
    title: "Nioh 2",
    titleKo: "인왕 2",
    genre: "Action RPG",
    tags: ["소울라이크", "전투", "장비", "보스전"],
    mood: ["도전적", "긴장감"],
    description: "복잡한 자세 전환과 장비 빌드가 깊이 있는 액션 RPG"
  },
  {
    id: "persona-5-royal",
    title: "Persona 5 Royal",
    titleKo: "페르소나 5 더 로열",
    genre: "JRPG",
    tags: ["턴제", "스토리", "생활", "파티"],
    mood: ["감성적", "서사적"],
    description: "학교 생활과 던전 공략이 결합된 스타일리시 턴제 JRPG"
  },
  {
    id: "dragon-quest-xi-s",
    title: "Dragon Quest XI S",
    titleKo: "드래곤 퀘스트 XI S",
    genre: "JRPG",
    tags: ["턴제", "스토리", "판타지", "파티"],
    mood: ["따뜻함", "모험적"],
    description: "전통적인 모험 서사와 안정적인 턴제 전투가 중심인 JRPG"
  },
  {
    id: "final-fantasy-vii-remake",
    title: "Final Fantasy VII Remake",
    titleKo: "파이널 판타지 VII 리메이크",
    genre: "Action RPG",
    tags: ["액션", "스토리", "파티", "SF"],
    mood: ["서사적", "몰입감"],
    description: "실시간 액션과 전술 선택이 섞인 시네마틱 액션 RPG"
  },
  {
    id: "nier-automata",
    title: "NieR: Automata",
    titleKo: "니어: 오토마타",
    genre: "Action RPG",
    tags: ["액션", "스토리", "SF", "철학"],
    mood: ["감성적", "서사적"],
    description: "빠른 액션과 철학적인 서사가 결합된 액션 RPG"
  },
  {
    id: "disco-elysium",
    title: "Disco Elysium",
    titleKo: "디스코 엘리시움",
    genre: "RPG",
    tags: ["스토리", "선택", "추리", "대화"],
    mood: ["서사적", "기묘함"],
    description: "대화와 선택, 심리 묘사가 핵심인 서사 중심 RPG"
  },
  {
    id: "divinity-original-sin-2",
    title: "Divinity: Original Sin 2",
    titleKo: "디비니티: 오리지널 신 2",
    genre: "RPG",
    tags: ["턴제", "스토리", "파티", "선택"],
    mood: ["전략적", "서사적"],
    description: "자유로운 상호작용과 전술 전투가 강점인 파티 기반 RPG"
  },
  {
    id: "rimworld",
    title: "RimWorld",
    titleKo: "림월드",
    genre: "Simulation",
    tags: ["생존", "건축", "자원관리", "스토리"],
    mood: ["전략적", "기묘함"],
    description: "정착민의 생존과 돌발 사건 관리가 핵심인 colony 시뮬레이션"
  },
  {
    id: "factorio",
    title: "Factorio",
    titleKo: "팩토리오",
    genre: "Automation",
    tags: ["건축", "자원관리", "제작", "자동화"],
    mood: ["집중", "창의적"],
    description: "자원 채굴부터 생산 라인 최적화까지 이어지는 자동화 게임"
  },
  {
    id: "oxygen-not-included",
    title: "Oxygen Not Included",
    titleKo: "옥시전 낫 인클루디드",
    genre: "Simulation",
    tags: ["생존", "건축", "자원관리", "과학"],
    mood: ["전략적", "집중"],
    description: "기지의 산소와 열, 자원을 세밀하게 관리하는 생존 시뮬레이션"
  },
  {
    id: "cities-skylines",
    title: "Cities: Skylines",
    titleKo: "시티즈: 스카이라인",
    genre: "Simulation",
    tags: ["건축", "도시", "자원관리", "확장"],
    mood: ["창의적", "집중"],
    description: "교통과 구역, 공공 서비스를 설계하는 도시 건설 시뮬레이션"
  },
  {
    id: "the-sims-4",
    title: "The Sims 4",
    titleKo: "심즈 4",
    genre: "Simulation",
    tags: ["생활", "꾸미기", "관계", "창작"],
    mood: ["자유로움", "창의적"],
    description: "캐릭터의 일상과 집, 관계를 자유롭게 꾸미는 생활 시뮬레이션"
  },
  {
    id: "fire-emblem-three-houses",
    title: "Fire Emblem: Three Houses",
    titleKo: "파이어 엠블렘 풍화설월",
    genre: "Strategy RPG",
    tags: ["턴제", "전술", "스토리", "관계"],
    mood: ["전략적", "서사적"],
    description: "학원 생활과 전술 전투, 분기 서사가 결합된 전략 RPG"
  },
  {
    id: "into-the-breach",
    title: "Into the Breach",
    titleKo: "인투 더 브리치",
    genre: "Strategy",
    tags: ["턴제", "전술", "SF", "퍼즐"],
    mood: ["전략적", "집중"],
    description: "작은 전장에서 수를 계산해 피해를 막는 턴제 전술 게임"
  },
  {
    id: "total-war-three-kingdoms",
    title: "Total War: Three Kingdoms",
    titleKo: "토탈 워: 삼국",
    genre: "Strategy",
    tags: ["전략", "전술", "역사", "전쟁"],
    mood: ["전략적", "서사적"],
    description: "삼국지 외교와 대규모 전투를 결합한 역사 전략 게임"
  },
  {
    id: "age-of-empires-ii-de",
    title: "Age of Empires II: Definitive Edition",
    titleKo: "에이지 오브 엠파이어 2: 결정판",
    genre: "Strategy",
    tags: ["전략", "건축", "전쟁", "자원관리"],
    mood: ["전략적", "집중"],
    description: "문명 성장과 실시간 전투 운영이 핵심인 클래식 RTS"
  },
  {
    id: "tetris-effect-connected",
    title: "Tetris Effect: Connected",
    titleKo: "테트리스 이펙트: 커넥티드",
    genre: "Puzzle",
    tags: ["퍼즐", "음악", "협동", "점수"],
    mood: ["아름다움", "집중"],
    description: "음악과 시각 연출이 몰입감을 높이는 리듬감 있는 퍼즐 게임"
  },
  {
    id: "return-of-the-obra-dinn",
    title: "Return of the Obra Dinn",
    titleKo: "리턴 오브 더 오브라 딘",
    genre: "Puzzle",
    tags: ["추리", "퍼즐", "관찰", "스토리"],
    mood: ["영리함", "기묘함"],
    description: "사건의 단서를 관찰해 승무원의 운명을 추적하는 추리 퍼즐 게임"
  },
  {
    id: "outer-wilds",
    title: "Outer Wilds",
    titleKo: "아우터 와일즈",
    genre: "Adventure",
    tags: ["탐험", "퍼즐", "우주", "스토리"],
    mood: ["모험적", "감성적"],
    description: "반복되는 시간 속 우주 비밀을 풀어가는 탐험 어드벤처"
  },
  {
    id: "super-mario-odyssey",
    title: "Super Mario Odyssey",
    titleKo: "슈퍼 마리오 오디세이",
    genre: "Platformer",
    tags: ["플랫포머", "탐험", "수집", "액션"],
    mood: ["유쾌함", "창의적"],
    description: "다채로운 왕국을 자유롭게 탐험하는 3D 플랫포머"
  },
  {
    id: "metroid-dread",
    title: "Metroid Dread",
    titleKo: "메트로이드 드레드",
    genre: "Metroidvania",
    tags: ["탐험", "플랫포머", "SF", "전투"],
    mood: ["긴장감", "몰입감"],
    description: "빠른 움직임과 긴장감 있는 추격이 특징인 메트로배니아"
  },
  {
    id: "cuphead",
    title: "Cuphead",
    titleKo: "컵헤드",
    genre: "Run and Gun",
    tags: ["액션", "보스전", "플랫포머", "협동"],
    mood: ["도전적", "유쾌함"],
    description: "고전 애니메이션풍 연출과 어려운 보스전이 핵심인 액션 게임"
  },
  {
    id: "the-last-of-us-part-ii",
    title: "The Last of Us Part II",
    titleKo: "더 라스트 오브 어스 파트 II",
    genre: "Action Adventure",
    tags: ["스토리", "잠입", "전투", "생존"],
    mood: ["서사적", "긴장감"],
    description: "강렬한 서사와 생존 전투가 결합된 시네마틱 액션 어드벤처"
  },
  {
    id: "uncharted-4",
    title: "Uncharted 4: A Thief's End",
    titleKo: "언차티드 4: 해적왕과 최후의 보물",
    genre: "Action Adventure",
    tags: ["액션", "스토리", "탐험", "퍼즐"],
    mood: ["모험적", "서사적"],
    description: "영화적인 연출과 보물 탐험이 어우러진 액션 어드벤처"
  },
  {
    id: "resident-evil-4-remake",
    title: "Resident Evil 4 Remake",
    titleKo: "바이오하자드 RE:4",
    genre: "Survival Horror",
    tags: ["생존", "공포", "전투", "자원관리"],
    mood: ["긴장감", "기묘함"],
    description: "자원 관리와 압박감 있는 전투가 중심인 생존 공포 게임"
  },
  {
    id: "zelda-breath-of-the-wild",
    title: "The Legend of Zelda: Breath of the Wild",
    titleKo: "젤다의 전설 브레스 오브 더 와일드",
    genre: "Open World",
    tags: ["오픈월드", "탐험", "퍼즐", "판타지"],
    mood: ["자유로움", "모험적"],
    description: "물리와 탐험의 자유도가 뛰어난 오픈월드 어드벤처"
  },
  {
    id: "zelda-tears-of-the-kingdom",
    title: "The Legend of Zelda: Tears of the Kingdom",
    titleKo: "젤다의 전설 티어스 오브 더 킹덤",
    genre: "Open World",
    tags: ["오픈월드", "탐험", "제작", "퍼즐"],
    mood: ["자유로움", "창의적"],
    description: "하늘과 지상을 넘나들며 장치를 조합하는 오픈월드 어드벤처"
  },
  {
    id: "dave-the-diver",
    title: "Dave the Diver",
    titleKo: "데이브 더 다이버",
    genre: "Adventure",
    tags: ["탐험", "생활", "수집", "경영"],
    mood: ["유쾌함", "따뜻함"],
    description: "해양 탐험과 초밥집 운영이 결합된 캐주얼 어드벤처"
  },
  {
    id: "vampire-survivors",
    title: "Vampire Survivors",
    titleKo: "뱀파이어 서바이버즈",
    genre: "Roguelike",
    tags: ["로그라이크", "액션", "생존", "빌드"],
    mood: ["빠른", "집중"],
    description: "자동 공격과 성장 빌드가 중독적인 생존 로그라이크"
  },
  {
    id: "balatro",
    title: "Balatro",
    titleKo: "발라트로",
    genre: "Card Strategy",
    tags: ["카드", "로그라이크", "전략", "덱빌딩"],
    mood: ["전략적", "집중"],
    description: "포커 조합과 변칙 카드 시너지가 핵심인 덱빌딩 로그라이크"
  },
  {
    id: "valheim",
    title: "Valheim",
    titleKo: "발헤임",
    genre: "Survival",
    tags: ["생존", "건축", "협동", "탐험"],
    mood: ["모험적", "자유로움"],
    description: "바이킹 세계에서 건축과 탐험, 보스전을 이어가는 생존 게임"
  },
  {
    id: "palworld",
    title: "Palworld",
    titleKo: "팰월드",
    genre: "Survival",
    tags: ["생존", "수집", "건축", "협동"],
    mood: ["자유로움", "유쾌함"],
    description: "생물 수집과 기지 건설, 전투가 결합된 오픈월드 생존 게임"
  },
  {
    id: "lethal-company",
    title: "Lethal Company",
    titleKo: "리썰 컴퍼니",
    genre: "Survival Horror",
    tags: ["공포", "협동", "탐험", "수집"],
    mood: ["긴장감", "유쾌함"],
    description: "폐시설에서 폐품을 모으는 협동 공포 생존 게임"
  },
  {
    id: "helldivers-2",
    title: "HELLDIVERS 2",
    titleKo: "헬다이버즈 2",
    genre: "Co-op Shooter",
    tags: ["협동", "슈터", "전투", "SF"],
    mood: ["긴장감", "유쾌함"],
    description: "분대 협동과 전장 혼란이 강점인 3인칭 협동 슈터"
  },
  {
    id: "deep-rock-galactic",
    title: "Deep Rock Galactic",
    titleKo: "딥 락 갤럭틱",
    genre: "Co-op Shooter",
    tags: ["협동", "슈터", "채굴", "SF"],
    mood: ["유쾌함", "모험적"],
    description: "동굴 탐사와 채굴, 외계 생물 전투가 결합된 협동 슈터"
  },
  {
    id: "risk-of-rain-2",
    title: "Risk of Rain 2",
    titleKo: "리스크 오브 레인 2",
    genre: "Roguelike",
    tags: ["로그라이크", "액션", "협동", "빌드"],
    mood: ["빠른", "도전적"],
    description: "아이템 중첩과 난이도 상승이 핵심인 3D 액션 로그라이크"
  },
  {
    id: "no-mans-sky",
    title: "No Man's Sky",
    titleKo: "노 맨즈 스카이",
    genre: "Open World",
    tags: ["오픈월드", "탐험", "우주", "제작"],
    mood: ["자유로움", "모험적"],
    description: "무한에 가까운 우주 탐험과 기지 건설이 중심인 오픈월드 게임"
  },
  {
    id: "satisfactory",
    title: "Satisfactory",
    titleKo: "새티스팩토리",
    genre: "Automation",
    tags: ["자동화", "건축", "자원관리", "협동"],
    mood: ["집중", "창의적"],
    description: "거대한 3D 공장과 생산 라인을 설계하는 자동화 게임"
  },
  {
    id: "hi-fi-rush",
    title: "Hi-Fi RUSH",
    titleKo: "하이파이 러시",
    genre: "Action Adventure",
    tags: ["액션", "음악", "전투", "스토리"],
    mood: ["유쾌함", "빠른"],
    description: "리듬에 맞춘 전투와 만화풍 연출이 강점인 액션 어드벤처"
  },
  {
    id: "sea-of-stars",
    title: "Sea of Stars",
    titleKo: "씨 오브 스타즈",
    genre: "JRPG",
    tags: ["턴제", "스토리", "판타지", "파티"],
    mood: ["따뜻함", "모험적"],
    description: "고전 JRPG 감성과 현대적인 턴제 전투가 어우러진 RPG"
  },
  {
    id: "tunic",
    title: "TUNIC",
    titleKo: "튜닉",
    genre: "Adventure",
    tags: ["탐험", "퍼즐", "전투", "판타지"],
    mood: ["영리함", "모험적"],
    description: "설명서를 해독하며 세계의 비밀을 찾아가는 어드벤처"
  },
  {
    id: "undertale",
    title: "Undertale",
    titleKo: "언더테일",
    genre: "RPG",
    tags: ["스토리", "선택", "전투", "픽셀"],
    mood: ["감성적", "기묘함"],
    description: "전투와 대화 선택이 서사에 크게 영향을 주는 인디 RPG"
  },
  {
    id: "dredge",
    title: "DREDGE",
    titleKo: "드레지",
    genre: "Adventure",
    tags: ["탐험", "수집", "공포", "해양"],
    mood: ["기묘함", "긴장감"],
    description: "낚시와 업그레이드, 불길한 해양 미스터리가 결합된 어드벤처"
  },
  {
    id: "inscryption",
    title: "Inscryption",
    titleKo: "인스크립션",
    genre: "Card Strategy",
    tags: ["카드", "로그라이크", "퍼즐", "공포"],
    mood: ["기묘함", "영리함"],
    description: "카드 게임과 퍼즐, 메타 서사가 얽힌 기묘한 덱빌딩 게임"
  },
  {
    id: "cult-of-the-lamb",
    title: "Cult of the Lamb",
    titleKo: "컬트 오브 더 램",
    genre: "Roguelike",
    tags: ["로그라이크", "경영", "액션", "기지"],
    mood: ["기묘함", "유쾌함"],
    description: "던전 액션과 교단 운영이 섞인 귀여운 분위기의 로그라이크"
  },
  {
    id: "lies-of-p",
    title: "Lies of P",
    titleKo: "P의 거짓",
    genre: "Action RPG",
    tags: ["소울라이크", "전투", "보스전", "다크판타지"],
    mood: ["도전적", "긴장감"],
    description: "동화 피노키오를 어둡게 재해석한 소울라이크 액션 RPG"
  },
  {
    id: "armored-core-vi",
    title: "Armored Core VI: Fires of Rubicon",
    titleKo: "아머드 코어 VI 루비콘의 화염",
    genre: "Action",
    tags: ["액션", "전투", "커스터마이징", "SF"],
    mood: ["빠른", "도전적"],
    description: "고속 메카 전투와 기체 조립이 핵심인 액션 게임"
  },
  {
    id: "remnant-2",
    title: "Remnant II",
    titleKo: "렘넌트 2",
    genre: "Action RPG",
    tags: ["슈터", "협동", "소울라이크", "전투"],
    mood: ["도전적", "긴장감"],
    description: "총기 전투와 보스 공략, 협동 플레이가 결합된 액션 RPG"
  },
  {
    id: "phasmophobia",
    title: "Phasmophobia",
    titleKo: "파스모포비아",
    genre: "Survival Horror",
    tags: ["공포", "협동", "추리", "탐험"],
    mood: ["긴장감", "기묘함"],
    description: "장비로 유령의 정체를 조사하는 협동 공포 게임"
  },
  {
    id: "project-zomboid",
    title: "Project Zomboid",
    titleKo: "프로젝트 좀보이드",
    genre: "Survival",
    tags: ["생존", "좀비", "자원관리", "협동"],
    mood: ["긴장감", "전략적"],
    description: "좀비 아포칼립스에서 생활과 자원을 관리하는 하드코어 생존 게임"
  },
  {
    id: "binding-of-isaac-rebirth",
    title: "The Binding of Isaac: Rebirth",
    titleKo: "아이작의 번제: 리버스",
    genre: "Roguelike",
    tags: ["로그라이크", "액션", "아이템", "던전"],
    mood: ["기묘함", "도전적"],
    description: "무작위 아이템 조합과 방 단위 전투가 핵심인 로그라이크"
  },
  {
    id: "euro-truck-simulator-2",
    title: "Euro Truck Simulator 2",
    titleKo: "유로 트럭 시뮬레이터 2",
    genre: "Simulation",
    tags: ["운전", "경영", "탐험", "생활"],
    mood: ["차분함", "집중"],
    description: "유럽 도로를 달리며 화물을 운송하는 트럭 운전 시뮬레이션"
  },
  {
    id: "among-us",
    title: "Among Us",
    titleKo: "어몽 어스",
    genre: "Social Deduction",
    tags: ["협동", "추리", "파티", "심리전"],
    mood: ["유쾌함", "긴장감"],
    description: "크루원과 임포스터의 심리전이 핵심인 멀티플레이 추리 게임"
  },
  {
    id: "papers-please",
    title: "Papers, Please",
    titleKo: "페이퍼스, 플리즈",
    genre: "Simulation",
    tags: ["추리", "선택", "스토리", "관리"],
    mood: ["긴장감", "기묘함"],
    description: "입국 심사관의 판단과 선택을 다루는 독특한 서류 심사 시뮬레이션"
  },
  {
    id: "hotline-miami",
    title: "Hotline Miami",
    titleKo: "핫라인 마이애미",
    genre: "Action",
    tags: ["액션", "전투", "속도감", "픽셀"],
    mood: ["빠른", "긴장감"],
    description: "빠른 판단과 반복 도전이 강렬한 탑다운 액션 게임"
  },
  {
    id: "ftl",
    title: "FTL: Faster Than Light",
    titleKo: "FTL: 패스터 댄 라이트",
    genre: "Strategy",
    tags: ["전략", "우주", "자원관리", "로그라이크"],
    mood: ["전략적", "긴장감"],
    description: "우주선을 관리하며 위기를 넘기는 전략 로그라이크"
  },
  {
    id: "stanley-parable-ultra-deluxe",
    title: "The Stanley Parable: Ultra Deluxe",
    titleKo: "스탠리 패러블: 울트라 디럭스",
    genre: "Adventure",
    tags: ["스토리", "선택", "유머", "탐험"],
    mood: ["기묘함", "유쾌함"],
    description: "내레이션과 선택을 비트는 실험적인 스토리 어드벤처"
  },
  {
    id: "a-short-hike",
    title: "A Short Hike",
    titleKo: "어 쇼트 하이크",
    genre: "Adventure",
    tags: ["탐험", "생활", "수집", "힐링"],
    mood: ["따뜻함", "차분함"],
    description: "작은 섬을 자유롭게 오르내리는 짧고 따뜻한 탐험 어드벤처"
  },
  {
    id: "spiritfarer",
    title: "Spiritfarer",
    titleKo: "스피릿페어러",
    genre: "Simulation",
    tags: ["생활", "제작", "스토리", "관계"],
    mood: ["감성적", "따뜻함"],
    description: "영혼을 배웅하며 배를 확장하고 관계를 쌓는 감성 시뮬레이션"
  },
  {
    id: "inside",
    title: "INSIDE",
    titleKo: "인사이드",
    genre: "Puzzle",
    tags: ["퍼즐", "플랫포머", "스토리", "공포"],
    mood: ["기묘함", "긴장감"],
    description: "어두운 세계를 통과하며 환경 퍼즐을 해결하는 시네마틱 퍼즐 게임"
  },
  {
    id: "limbo",
    title: "LIMBO",
    titleKo: "림보",
    genre: "Puzzle",
    tags: ["퍼즐", "플랫포머", "공포", "관찰"],
    mood: ["기묘함", "차분함"],
    description: "흑백 실루엣 세계에서 위험을 피해 나아가는 퍼즐 플랫포머"
  },
  {
    id: "fez",
    title: "FEZ",
    titleKo: "페즈",
    genre: "Puzzle",
    tags: ["퍼즐", "플랫포머", "탐험", "관찰"],
    mood: ["영리함", "차분함"],
    description: "2D와 3D 시점을 돌려 숨은 길을 찾는 퍼즐 플랫포머"
  },
  {
    id: "spelunky-2",
    title: "Spelunky 2",
    titleKo: "스펠렁키 2",
    genre: "Roguelike",
    tags: ["로그라이크", "플랫포머", "탐험", "협동"],
    mood: ["도전적", "긴장감"],
    description: "매번 달라지는 동굴을 탐험하는 고난도 로그라이크 플랫포머"
  },
  {
    id: "shovel-knight-treasure-trove",
    title: "Shovel Knight: Treasure Trove",
    titleKo: "쇼벨 나이트: 트레저 트로브",
    genre: "Platformer",
    tags: ["플랫포머", "액션", "보스전", "픽셀"],
    mood: ["유쾌함", "도전적"],
    description: "고전 액션 플랫포머 감성을 현대적으로 다듬은 인디 게임"
  },
  {
    id: "katana-zero",
    title: "Katana ZERO",
    titleKo: "카타나 제로",
    genre: "Action",
    tags: ["액션", "스토리", "전투", "픽셀"],
    mood: ["빠른", "긴장감"],
    description: "시간 조작과 즉사 액션이 결합된 스타일리시 액션 게임"
  },
  {
    id: "hyper-light-drifter",
    title: "Hyper Light Drifter",
    titleKo: "하이퍼 라이트 드리프터",
    genre: "Action Adventure",
    tags: ["액션", "탐험", "전투", "픽셀"],
    mood: ["감성적", "도전적"],
    description: "묵직한 분위기와 빠른 전투가 어우러진 액션 어드벤처"
  },
  {
    id: "enter-the-gungeon",
    title: "Enter the Gungeon",
    titleKo: "엔터 더 건전",
    genre: "Roguelike",
    tags: ["로그라이크", "슈터", "액션", "협동"],
    mood: ["빠른", "도전적"],
    description: "총알 지옥 전투와 아이템 조합이 핵심인 로그라이크 슈터"
  },
  {
    id: "darkest-dungeon",
    title: "Darkest Dungeon",
    titleKo: "다키스트 던전",
    genre: "Strategy",
    tags: ["턴제", "전략", "자원관리", "공포"],
    mood: ["긴장감", "기묘함"],
    description: "스트레스와 위험을 관리하며 던전을 공략하는 어두운 전략 RPG"
  },
  {
    id: "firewatch",
    title: "Firewatch",
    titleKo: "파이어워치",
    genre: "Adventure",
    tags: ["스토리", "탐험", "대화", "미스터리"],
    mood: ["감성적", "차분함"],
    description: "숲속 감시탑에서 벌어지는 관계와 미스터리를 따라가는 어드벤처"
  },
  {
    id: "gris",
    title: "GRIS",
    titleKo: "그리스",
    genre: "Platformer",
    tags: ["플랫포머", "감성", "퍼즐", "예술"],
    mood: ["아름다움", "감성적"],
    description: "수채화 같은 비주얼과 감성적인 진행이 돋보이는 플랫포머"
  },
  {
    id: "edith-finch",
    title: "What Remains of Edith Finch",
    titleKo: "왓 리메인즈 오브 에디스 핀치",
    genre: "Adventure",
    tags: ["스토리", "탐험", "미스터리", "가족"],
    mood: ["감성적", "서사적"],
    description: "한 가족의 이야기를 다양한 방식으로 체험하는 서사 어드벤처"
  },
  {
    id: "baba-is-you",
    title: "Baba Is You",
    titleKo: "바바 이즈 유",
    genre: "Puzzle",
    tags: ["퍼즐", "규칙", "논리", "창의"],
    mood: ["영리함", "집중"],
    description: "규칙 문장을 직접 바꿔 해법을 만드는 창의적인 퍼즐 게임"
  },
  {
    id: "untitled-goose-game",
    title: "Untitled Goose Game",
    titleKo: "언타이틀드 구스 게임",
    genre: "Puzzle",
    tags: ["퍼즐", "잠입", "유머", "생활"],
    mood: ["유쾌함", "창의적"],
    description: "마을 사람들을 골탕 먹이며 목표를 해결하는 코미디 퍼즐 게임"
  },
  {
    id: "loop-hero",
    title: "Loop Hero",
    titleKo: "루프 히어로",
    genre: "Strategy",
    tags: ["전략", "덱빌딩", "로그라이크", "자동전투"],
    mood: ["전략적", "집중"],
    description: "타일과 카드를 배치해 반복 루프를 설계하는 전략 게임"
  },
  {
    id: "rain-world",
    title: "Rain World",
    titleKo: "레인 월드",
    genre: "Survival",
    tags: ["생존", "탐험", "플랫포머", "생태계"],
    mood: ["긴장감", "기묘함"],
    description: "거친 생태계 속에서 살아남아 이동하는 생존 플랫포머"
  },
  {
    id: "night-in-the-woods",
    title: "Night in the Woods",
    titleKo: "나이트 인 더 우즈",
    genre: "Adventure",
    tags: ["스토리", "대화", "관계", "미스터리"],
    mood: ["감성적", "기묘함"],
    description: "작은 마을의 관계와 불안을 그리는 스토리 중심 어드벤처"
  },
  {
    id: "oxenfree",
    title: "Oxenfree",
    titleKo: "옥센프리",
    genre: "Adventure",
    tags: ["스토리", "대화", "미스터리", "선택"],
    mood: ["기묘함", "감성적"],
    description: "무전기를 통해 섬의 미스터리를 풀어가는 대화 중심 어드벤처"
  },
  {
    id: "crypt-of-the-necrodancer",
    title: "Crypt of the NecroDancer",
    titleKo: "크립트 오브 더 네크로댄서",
    genre: "Roguelike",
    tags: ["로그라이크", "음악", "리듬", "던전"],
    mood: ["빠른", "도전적"],
    description: "박자에 맞춰 움직이며 던전을 공략하는 리듬 로그라이크"
  },
  {
    id: "superhot",
    title: "SUPERHOT",
    titleKo: "슈퍼핫",
    genre: "Action",
    tags: ["액션", "슈터", "퍼즐", "전투"],
    mood: ["영리함", "긴장감"],
    description: "움직일 때만 시간이 흐르는 독특한 규칙의 액션 슈터"
  },
  {
    id: "brotato",
    title: "Brotato",
    titleKo: "브로타토",
    genre: "Roguelike",
    tags: ["로그라이크", "액션", "생존", "빌드"],
    mood: ["빠른", "집중"],
    description: "짧은 웨이브와 무기 빌드가 핵심인 캐주얼 액션 로그라이크"
  },
  {
    id: "unpacking",
    title: "Unpacking",
    titleKo: "언패킹",
    genre: "Puzzle",
    tags: ["퍼즐", "생활", "정리", "스토리"],
    mood: ["차분함", "따뜻함"],
    description: "물건을 정리하며 한 사람의 삶을 따라가는 조용한 퍼즐 게임"
  },
  {
    id: "dorfromantik",
    title: "Dorfromantik",
    titleKo: "도르프로만틱",
    genre: "Puzzle",
    tags: ["퍼즐", "건축", "타일", "차분함"],
    mood: ["차분함", "집중"],
    description: "타일을 이어 평화로운 풍경을 만드는 차분한 퍼즐 게임"
  },
  {
    id: "mini-motorways",
    title: "Mini Motorways",
    titleKo: "미니 모터웨이즈",
    genre: "Strategy",
    tags: ["전략", "교통", "퍼즐", "도시"],
    mood: ["집중", "영리함"],
    description: "도로망을 설계해 도시의 교통 흐름을 유지하는 전략 퍼즐 게임"
  },
  {
    id: "half-life-2",
    title: "Half-Life 2",
    titleKo: "하프라이프 2",
    genre: "Action",
    tags: ["FPS", "스토리", "물리엔진", "SF"],
    mood: ["몰입감", "긴장감"],
    description: "물리 기반 퍼즐과 밀도 높은 연출이 결합된 SF FPS의 고전"
  },
  {
    id: "portal",
    title: "Portal",
    titleKo: "포탈",
    genre: "Puzzle",
    tags: ["퍼즐", "물리", "유머", "SF"],
    mood: ["영리함", "유쾌함"],
    description: "포털 하나로 세상을 뒤집는 짧고 완벽한 퍼즐 게임"
  },
  {
    id: "counter-strike-2",
    title: "Counter-Strike 2",
    titleKo: "카운터 스트라이크 2",
    genre: "Shooter",
    tags: ["FPS", "대전", "전술", "e스포츠"],
    mood: ["긴장감", "집중"],
    description: "정밀한 조준과 팀 전술이 승부를 가르는 대표 경쟁 FPS"
  },
  {
    id: "gta-5",
    title: "Grand Theft Auto V",
    titleKo: "그랜드 테프트 오토 5",
    genre: "Open World",
    tags: ["오픈월드", "범죄", "탐험", "다인원"],
    mood: ["자유로움", "몰입감"],
    description: "세 주인공의 이야기와 방대한 도시를 자유롭게 오가는 오픈월드 범죄극"
  },
  {
    id: "skyrim",
    title: "The Elder Scrolls V: Skyrim",
    titleKo: "엘더스크롤 5: 스카이림",
    genre: "RPG",
    tags: ["오픈월드", "판타지", "탐험", "모드"],
    mood: ["자유로움", "몰입감"],
    description: "끝없는 탐험과 자유도가 특징인 판타지 오픈월드 RPG의 기준점"
  },
  {
    id: "fallout-4",
    title: "Fallout 4",
    titleKo: "폴아웃 4",
    genre: "RPG",
    tags: ["오픈월드", "포스트아포칼립스", "제작", "선택"],
    mood: ["자유로움", "기묘함"],
    description: "폐허가 된 세계를 탐험하며 기지를 짓고 이야기를 만드는 오픈월드 RPG"
  },
  {
    id: "bioshock-infinite",
    title: "BioShock Infinite",
    titleKo: "바이오쇼크 인피니트",
    genre: "Action",
    tags: ["FPS", "스토리", "SF", "선택"],
    mood: ["서사적", "몰입감"],
    description: "하늘 위 도시를 배경으로 한 반전 가득한 스토리 중심 FPS"
  },
  {
    id: "dishonored-2",
    title: "Dishonored 2",
    titleKo: "디스아너드 2",
    genre: "Action",
    tags: ["잠입", "액션", "선택", "판타지"],
    mood: ["전략적", "긴장감"],
    description: "잠입과 전투 중 원하는 방식을 골라 목표를 처리하는 초자연 액션 게임"
  },
  {
    id: "doom-eternal",
    title: "DOOM Eternal",
    titleKo: "둠 이터널",
    genre: "Action",
    tags: ["FPS", "전투", "SF", "속도감"],
    mood: ["빠른", "도전적"],
    description: "쉴 새 없이 몰아치는 전투 리듬이 중독적인 하드코어 FPS"
  },
  {
    id: "control",
    title: "Control",
    titleKo: "컨트롤",
    genre: "Action Adventure",
    tags: ["초자연", "전투", "탐험", "SF"],
    mood: ["기묘함", "몰입감"],
    description: "초자연적인 힘과 변형되는 공간을 활용하는 3인칭 액션 어드벤처"
  },
  {
    id: "resident-evil-village",
    title: "Resident Evil Village",
    titleKo: "바이오하자드 빌리지",
    genre: "Survival Horror",
    tags: ["공포", "전투", "자원관리", "탐험"],
    mood: ["긴장감", "기묘함"],
    description: "기괴한 마을을 탐험하며 생존을 다투는 1인칭 생존 공포 게임"
  },
  {
    id: "death-stranding",
    title: "Death Stranding",
    titleKo: "데스 스트랜딩",
    genre: "Action Adventure",
    tags: ["오픈월드", "탐험", "비동기협동", "SF"],
    mood: ["기묘함", "서사적"],
    description: "황량한 대지를 가로질러 세상을 다시 연결하는 독특한 배달 어드벤처"
  },
  {
    id: "hogwarts-legacy",
    title: "Hogwarts Legacy",
    titleKo: "호그와트 레거시",
    genre: "Action RPG",
    tags: ["오픈월드", "판타지", "마법", "탐험"],
    mood: ["몰입감", "따뜻함"],
    description: "마법 학교와 주변 세계를 자유롭게 누비는 오픈월드 액션 RPG"
  },
  {
    id: "starfield",
    title: "Starfield",
    titleKo: "스타필드",
    genre: "RPG",
    tags: ["오픈월드", "SF", "탐험", "우주"],
    mood: ["자유로움", "모험적"],
    description: "수많은 행성을 탐험하고 우주선을 꾸미는 방대한 스케일의 SF RPG"
  },
  {
    id: "diablo-4",
    title: "Diablo IV",
    titleKo: "디아블로 4",
    genre: "Action RPG",
    tags: ["핵앤슬래시", "협동", "장비", "다크판타지"],
    mood: ["도전적", "몰입감"],
    description: "끝없는 사냥과 장비 파밍이 중독적인 다크 판타지 액션 RPG"
  },
  {
    id: "path-of-exile",
    title: "Path of Exile",
    titleKo: "패스 오브 엑자일",
    genre: "Action RPG",
    tags: ["핵앤슬래시", "빌드", "무료", "다크판타지"],
    mood: ["전략적", "도전적"],
    description: "복잡하고 깊이 있는 빌드 설계가 매력인 무료 핵앤슬래시 RPG"
  },
  {
    id: "warframe",
    title: "Warframe",
    titleKo: "워프레임",
    genre: "Co-op Shooter",
    tags: ["협동", "슈터", "SF", "무료"],
    mood: ["빠른", "몰입감"],
    description: "다양한 전투 슈트로 임무를 함께 수행하는 무료 협동 슈터"
  },
  {
    id: "apex-legends",
    title: "Apex Legends",
    titleKo: "에이펙스 레전드",
    genre: "Shooter",
    tags: ["배틀로얄", "슈터", "협동", "무료"],
    mood: ["빠른", "긴장감"],
    description: "개성 있는 캐릭터와 팀 전술이 돋보이는 배틀로얄 슈터"
  },
  {
    id: "rust",
    title: "Rust",
    titleKo: "러스트",
    genre: "Survival",
    tags: ["생존", "제작", "다인원", "PvP"],
    mood: ["긴장감", "전략적"],
    description: "자원과 신뢰를 두고 다투는 살벌한 멀티플레이 생존 게임"
  },
  {
    id: "ark-survival-evolved",
    title: "ARK: Survival Evolved",
    titleKo: "아크: 서바이벌 이볼브드",
    genre: "Survival",
    tags: ["생존", "공룡", "제작", "탐험"],
    mood: ["모험적", "긴장감"],
    description: "공룡이 뛰노는 섬에서 길들이고 건설하며 살아남는 생존 게임"
  },
  {
    id: "sons-of-the-forest",
    title: "Sons Of The Forest",
    titleKo: "선즈 오브 더 포레스트",
    genre: "Survival Horror",
    tags: ["생존", "공포", "제작", "협동"],
    mood: ["긴장감", "기묘함"],
    description: "식인종이 도사리는 숲에서 살아남는 오픈월드 생존 공포 게임"
  },
  {
    id: "v-rising",
    title: "V Rising",
    titleKo: "브이 라이징",
    genre: "Survival",
    tags: ["생존", "뱀파이어", "제작", "PvP"],
    mood: ["긴장감", "모험적"],
    description: "뱀파이어가 되어 성을 쌓고 세력을 넓히는 오픈월드 생존 게임"
  },
  {
    id: "dying-light-2",
    title: "Dying Light 2 Stay Human",
    titleKo: "다잉 라이트 2",
    genre: "Action RPG",
    tags: ["파쿠르", "좀비", "오픈월드", "선택"],
    mood: ["긴장감", "빠른"],
    description: "파쿠르로 도시를 누비며 좀비 무리를 피해 다니는 오픈월드 액션"
  },
  {
    id: "left-4-dead-2",
    title: "Left 4 Dead 2",
    titleKo: "레프트 4 데드 2",
    genre: "Co-op Shooter",
    tags: ["협동", "좀비", "슈터", "생존"],
    mood: ["긴장감", "빠른"],
    description: "네 명이 힘을 합쳐 좀비 무리를 뚫고 나아가는 협동 슈터의 명작"
  },
  {
    id: "team-fortress-2",
    title: "Team Fortress 2",
    titleKo: "팀 포트리스 2",
    genre: "Shooter",
    tags: ["슈터", "대전", "무료", "유머"],
    mood: ["유쾌함", "빠른"],
    description: "개성 강한 9개 클래스로 팀 전투를 즐기는 무료 클래식 슈터"
  },
  {
    id: "monster-hunter-rise",
    title: "Monster Hunter Rise",
    titleKo: "몬스터 헌터 라이즈",
    genre: "Action RPG",
    tags: ["액션", "협동", "전투", "제작"],
    mood: ["도전적", "모험적"],
    description: "날렵한 이동기와 사냥 액션이 강화된 몬스터 헌터 시리즈"
  },
  {
    id: "street-fighter-6",
    title: "Street Fighter 6",
    titleKo: "스트리트 파이터 6",
    genre: "Fighting",
    tags: ["격투", "대전", "e스포츠", "콤보"],
    mood: ["빠른", "긴장감"],
    description: "정교한 타격감과 콤보 설계가 살아있는 대표 격투 게임"
  },
  {
    id: "tekken-8",
    title: "TEKKEN 8",
    titleKo: "철권 8",
    genre: "Fighting",
    tags: ["격투", "대전", "e스포츠", "콤보"],
    mood: ["빠른", "긴장감"],
    description: "화려한 3D 격투 액션과 깊이 있는 시스템을 갖춘 철권 시리즈 최신작"
  },
  {
    id: "rocket-league",
    title: "Rocket League",
    titleKo: "로켓 리그",
    genre: "Sports",
    tags: ["스포츠", "자동차", "대전", "협동"],
    mood: ["빠른", "유쾌함"],
    description: "로켓을 단 자동차로 축구를 즐기는 독창적인 스포츠 게임"
  },
  {
    id: "human-fall-flat",
    title: "Human: Fall Flat",
    titleKo: "휴먼: 폴 플랫",
    genre: "Co-op Adventure",
    tags: ["협동", "물리", "퍼즐", "유머"],
    mood: ["유쾌함", "창의적"],
    description: "흐물흐물한 캐릭터로 물리 퍼즐을 함께 풀어가는 코미디 협동 게임"
  },
  {
    id: "overcooked-2",
    title: "Overcooked! 2",
    titleKo: "오버쿡드 2",
    genre: "Co-op Adventure",
    tags: ["협동", "요리", "파티", "타이밍"],
    mood: ["유쾌함", "빠른"],
    description: "정신없는 주방에서 손발을 맞춰야 하는 협동 요리 파티 게임"
  },
  {
    id: "hunt-showdown",
    title: "Hunt: Showdown 1896",
    titleKo: "헌트: 쇼다운",
    genre: "Survival Horror",
    tags: ["PvPvE", "슈터", "현상금", "긴장감"],
    mood: ["긴장감", "전략적"],
    description: "괴물과 다른 플레이어를 동시에 상대하는 하드코어 현상금 사냥 슈터"
  },
  {
    id: "metro-exodus",
    title: "Metro Exodus",
    titleKo: "메트로 엑소더스",
    genre: "Action",
    tags: ["FPS", "생존", "포스트아포칼립스", "스토리"],
    mood: ["긴장감", "서사적"],
    description: "폐허가 된 러시아를 열차로 가로지르는 몰입감 짙은 생존 FPS"
  },
  {
    id: "titanfall-2",
    title: "Titanfall 2",
    titleKo: "타이탄폴 2",
    genre: "Action",
    tags: ["FPS", "메카", "이동기", "스토리"],
    mood: ["빠른", "몰입감"],
    description: "거대 로봇과 날렵한 파쿠르 이동이 결합된 완성도 높은 FPS"
  },
  {
    id: "borderlands-3",
    title: "Borderlands 3",
    titleKo: "보더랜드 3",
    genre: "Action RPG",
    tags: ["루팅", "협동", "슈터", "유머"],
    mood: ["유쾌함", "빠른"],
    description: "수많은 총기를 파밍하며 즐기는 코믹한 협동 루터 슈터"
  },
  {
    id: "deltarune",
    title: "Deltarune",
    titleKo: "델타룬",
    genre: "RPG",
    tags: ["턴제", "스토리", "선택", "유머"],
    mood: ["감성적", "기묘함"],
    description: "언더테일 세계관을 잇는 개성 넘치는 턴제 스토리 RPG"
  },
  {
    id: "cocoon",
    title: "COCOON",
    titleKo: "코쿤",
    genre: "Puzzle",
    tags: ["퍼즐", "탐험", "세계관", "미니멀"],
    mood: ["영리함", "몰입감"],
    description: "세계 속의 세계를 오가며 퍼즐을 풀어가는 미니멀한 탐험 퍼즐"
  },
  {
    id: "chicory",
    title: "Chicory: A Colorful Tale",
    titleKo: "치커리: 컬러풀 테일",
    genre: "Adventure",
    tags: ["탐험", "그림", "퍼즐", "감성"],
    mood: ["따뜻함", "감성적"],
    description: "붓으로 세상에 색을 칠하며 나아가는 따뜻한 탐험 어드벤처"
  },
  {
    id: "neon-white",
    title: "Neon White",
    titleKo: "네온 화이트",
    genre: "Action",
    tags: ["스피드런", "FPS", "플랫포머", "스토리"],
    mood: ["빠른", "집중"],
    description: "카드를 무기와 이동기로 바꿔 쓰는 초고속 스피드런 액션 게임"
  },
  {
    id: "pizza-tower",
    title: "Pizza Tower",
    titleKo: "피자 타워",
    genre: "Platformer",
    tags: ["플랫포머", "속도감", "픽셀", "유머"],
    mood: ["빠른", "유쾌함"],
    description: "끊임없이 질주하는 하이텐션 2D 플랫포머"
  },
  {
    id: "signalis",
    title: "SIGNALIS",
    titleKo: "시그널리스",
    genre: "Survival Horror",
    tags: ["생존", "공포", "SF", "스토리"],
    mood: ["긴장감", "기묘함"],
    description: "레트로 감성의 그래픽과 짙은 분위기가 인상적인 생존 공포 게임"
  },
  {
    id: "pentiment",
    title: "Pentiment",
    titleKo: "펜티먼트",
    genre: "Adventure",
    tags: ["스토리", "추리", "선택", "역사"],
    mood: ["서사적", "감성적"],
    description: "중세 마을의 살인 사건을 추적하는 독특한 그림체의 추리 어드벤처"
  },
  {
    id: "astroneer",
    title: "Astroneer",
    titleKo: "애스트로니어",
    genre: "Sandbox",
    tags: ["탐험", "제작", "협동", "우주"],
    mood: ["편안함", "창의적"],
    description: "행성 지형을 직접 깎고 다지며 탐험하는 아기자기한 우주 샌드박스"
  },
  {
    id: "core-keeper",
    title: "Core Keeper",
    titleKo: "코어 키퍼",
    genre: "Sandbox",
    tags: ["채굴", "제작", "협동", "탐험"],
    mood: ["편안함", "몰입감"],
    description: "지하 동굴을 채굴하고 개척하는 2D 협동 샌드박스 게임"
  },
  {
    id: "raft",
    title: "Raft",
    titleKo: "래프트",
    genre: "Survival",
    tags: ["생존", "제작", "해양", "협동"],
    mood: ["편안함", "모험적"],
    description: "작은 뗏목 하나에서 시작해 바다를 개척하는 협동 생존 게임"
  },
  {
    id: "a-plague-tale-requiem",
    title: "A Plague Tale: Requiem",
    titleKo: "어 플레이그 테일: 레퀴엠",
    genre: "Action Adventure",
    tags: ["잠입", "스토리", "쥐떼", "가족"],
    mood: ["서사적", "긴장감"],
    description: "쥐떼가 뒤덮은 세계에서 남매의 여정을 그리는 잠입 액션 어드벤처"
  },
  {
    id: "little-nightmares-2",
    title: "Little Nightmares II",
    titleKo: "리틀 나이트메어 2",
    genre: "Puzzle",
    tags: ["퍼즐", "공포", "플랫포머", "동행"],
    mood: ["기묘함", "긴장감"],
    description: "기괴한 세계를 동료와 함께 헤쳐나가는 공포 퍼즐 플랫포머"
  },
  {
    id: "kena-bridge-of-spirits",
    title: "Kena: Bridge of Spirits",
    titleKo: "케나: 브릿지 오브 스피릿",
    genre: "Action Adventure",
    tags: ["전투", "탐험", "정령", "감성"],
    mood: ["따뜻함", "감성적"],
    description: "귀여운 정령들과 함께 잊혀진 마을을 치유하는 액션 어드벤처"
  },
  {
    id: "against-the-storm",
    title: "Against the Storm",
    titleKo: "어게인스트 더 스톰",
    genre: "Strategy",
    tags: ["도시건설", "로그라이크", "자원관리", "다크판타지"],
    mood: ["전략적", "집중"],
    description: "폭풍이 몰아치는 세계에서 반복해서 마을을 재건하는 전략 로그라이크"
  },
  {
    id: "terra-nil",
    title: "Terra Nil",
    titleKo: "테라 닐",
    genre: "Simulation",
    tags: ["환경", "빌드", "역발상", "힐링"],
    mood: ["편안함", "창의적"],
    description: "황무지를 되살리고 흔적 없이 떠나는 역발상 환경 시뮬레이션"
  },
  {
    id: "wukong",
    title: "Black Myth: Wukong",
    titleKo: "검은 신화: 오공",
    genre: "Action RPG",
    tags: ["소울라이크", "전투", "신화", "보스전"],
    mood: ["도전적", "몰입감"],
    description: "서유기를 재해석한 화려한 액션과 웅장한 보스전이 특징인 소울라이크"
  }
];

const gameDetails = {
  "elden-ring": ["2022", "약 60-100시간", 5, "온라인 협동/침입", "PC, PlayStation, Xbox", "지원", "Metacritic 96 / Steam 매우 긍정적"],
  "dark-souls-3": ["2016", "약 35-60시간", 5, "온라인 협동/침입", "PC, PlayStation, Xbox", "지원", "Metacritic 89 / Steam 매우 긍정적"],
  "the-witcher-3": ["2015", "약 50-120시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 93 / Steam 압도적으로 긍정적"],
  "baldurs-gate-3": ["2023", "약 75-120시간", 4, "온라인 협동 최대 4명", "PC, PlayStation, Xbox", "지원", "Metacritic 96 / Steam 압도적으로 긍정적"],
  "stardew-valley": ["2016", "약 50-150시간", 2, "온라인 협동 최대 8명", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 89 / Steam 압도적으로 긍정적"],
  "animal-crossing": ["2020", "약 60시간 이상", 1, "온라인 최대 8명", "Switch", "지원", "Metacritic 90 / Steam 없음"],
  "minecraft": ["2011", "플레이 방식에 따라 크게 달라짐", 2, "온라인 다인원", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 93 / Steam 없음"],
  "terraria": ["2011", "약 50-100시간", 3, "온라인 최대 8명", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 83 / Steam 압도적으로 긍정적"],
  "hades": ["2020", "약 20-50시간", 4, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 93 / Steam 압도적으로 긍정적"],
  "dead-cells": ["2018", "약 20-60시간", 4, "싱글플레이", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 89 / Steam 압도적으로 긍정적"],
  "civilization-vi": ["2016", "약 40시간 이상", 3, "온라인 다인원", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 88 / Steam 매우 긍정적"],
  "xcom-2": ["2016", "약 30-50시간", 4, "싱글플레이", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 88 / Steam 매우 긍정적"],
  "portal-2": ["2011", "약 8-12시간", 2, "협동 2명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 95 / Steam 압도적으로 긍정적"],
  "the-witness": ["2016", "약 15-30시간", 4, "싱글플레이", "PC, PlayStation, Xbox, Mobile", "미지원", "Metacritic 87 / Steam 매우 긍정적"],
  "hollow-knight": ["2017", "약 25-50시간", 4, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 90 / Steam 압도적으로 긍정적"],
  "ori-will-of-the-wisps": ["2020", "약 12-20시간", 3, "싱글플레이", "PC, Xbox, Switch", "지원", "Metacritic 90 / Steam 압도적으로 긍정적"],
  "celeste": ["2018", "약 8-20시간", 5, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 94 / Steam 압도적으로 긍정적"],
  "slay-the-spire": ["2019", "약 20-100시간", 4, "싱글플레이", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 89 / Steam 압도적으로 긍정적"],
  "subnautica": ["2018", "약 25-50시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 87 / Steam 압도적으로 긍정적"],
  "dont-starve": ["2013", "약 20시간 이상", 4, "싱글플레이", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 79 / Steam 매우 긍정적"],
  "mass-effect-2": ["2010", "약 25-45시간", 3, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 96 / Steam 매우 긍정적"],
  "it-takes-two": ["2021", "약 12-15시간", 2, "협동 2명 전용", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 89 / Steam 압도적으로 긍정적"],
  "cyberpunk-2077": ["2020", "약 30-80시간", 3, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 86 / Steam 매우 긍정적"],
  "red-dead-redemption-2": ["2018", "약 50-100시간", 3, "온라인 다인원", "PC, PlayStation, Xbox", "지원", "Metacritic 97 / Steam 매우 긍정적"],
  "god-of-war": ["2018", "약 20-40시간", 3, "싱글플레이", "PC, PlayStation", "지원", "Metacritic 94 / Steam 압도적으로 긍정적"],
  "horizon-zero-dawn": ["2017", "약 35-70시간", 3, "싱글플레이", "PC, PlayStation", "지원", "Metacritic 89 / Steam 매우 긍정적"],
  "ghost-of-tsushima": ["2020", "약 30-60시간", 3, "온라인 협동 최대 4명", "PC, PlayStation", "지원", "Metacritic 83 / Steam 매우 긍정적"],
  "monster-hunter-world": ["2018", "약 50-100시간", 4, "온라인 협동 최대 4명", "PC, PlayStation, Xbox", "지원", "Metacritic 90 / Steam 매우 긍정적"],
  "sekiro": ["2019", "약 30-50시간", 5, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 90 / Steam 매우 긍정적"],
  "bloodborne": ["2015", "약 35-60시간", 5, "온라인 협동/침입", "PlayStation", "지원", "Metacritic 92 / Steam 없음"],
  "nioh-2": ["2020", "약 50-100시간", 5, "온라인 협동 최대 3명", "PC, PlayStation", "지원", "Metacritic 85 / Steam 매우 긍정적"],
  "persona-5-royal": ["2019", "약 90-120시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 95 / Steam 압도적으로 긍정적"],
  "dragon-quest-xi-s": ["2019", "약 60-100시간", 2, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 91 / Steam 매우 긍정적"],
  "final-fantasy-vii-remake": ["2020", "약 35-50시간", 3, "싱글플레이", "PC, PlayStation", "지원", "Metacritic 87 / Steam 매우 긍정적"],
  "nier-automata": ["2017", "약 25-60시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 88 / Steam 매우 긍정적"],
  "disco-elysium": ["2019", "약 20-40시간", 2, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 91 / Steam 매우 긍정적"],
  "divinity-original-sin-2": ["2017", "약 60-100시간", 4, "온라인 협동 최대 4명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 93 / Steam 압도적으로 긍정적"],
  "rimworld": ["2018", "약 50시간 이상", 4, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 87 / Steam 압도적으로 긍정적"],
  "factorio": ["2020", "약 50시간 이상", 4, "온라인 다인원", "PC, Switch", "지원", "Metacritic 90 / Steam 압도적으로 긍정적"],
  "oxygen-not-included": ["2019", "약 50시간 이상", 4, "싱글플레이", "PC", "지원", "Metacritic 86 / Steam 압도적으로 긍정적"],
  "cities-skylines": ["2015", "약 40시간 이상", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 85 / Steam 매우 긍정적"],
  "the-sims-4": ["2014", "플레이 방식에 따라 크게 달라짐", 1, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 70 / Steam 매우 긍정적"],
  "fire-emblem-three-houses": ["2019", "약 50-80시간", 3, "싱글플레이", "Switch", "지원", "Metacritic 89 / Steam 없음"],
  "into-the-breach": ["2018", "약 10-30시간", 4, "싱글플레이", "PC, Switch, Mobile", "지원", "Metacritic 90 / Steam 압도적으로 긍정적"],
  "total-war-three-kingdoms": ["2019", "약 30-80시간", 4, "온라인 2명", "PC", "지원", "Metacritic 85 / Steam 매우 긍정적"],
  "age-of-empires-ii-de": ["2019", "약 20시간 이상", 3, "온라인 다인원", "PC, Xbox", "지원", "Metacritic 84 / Steam 매우 긍정적"],
  "tetris-effect-connected": ["2018", "약 5-20시간", 2, "온라인/로컬 최대 3명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 89 / Steam 압도적으로 긍정적"],
  "return-of-the-obra-dinn": ["2018", "약 8-12시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 89 / Steam 압도적으로 긍정적"],
  "outer-wilds": ["2019", "약 15-25시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 85 / Steam 압도적으로 긍정적"],
  "super-mario-odyssey": ["2017", "약 12-30시간", 2, "로컬 2명", "Switch", "지원", "Metacritic 97 / Steam 없음"],
  "metroid-dread": ["2021", "약 8-15시간", 4, "싱글플레이", "Switch", "지원", "Metacritic 88 / Steam 없음"],
  "cuphead": ["2017", "약 10-20시간", 5, "로컬 협동 2명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 88 / Steam 압도적으로 긍정적"],
  "the-last-of-us-part-ii": ["2020", "약 25-35시간", 3, "싱글플레이", "PlayStation", "지원", "Metacritic 93 / Steam 없음"],
  "uncharted-4": ["2016", "약 15-30시간", 2, "온라인 다인원", "PC, PlayStation", "지원", "Metacritic 93 / Steam 매우 긍정적"],
  "resident-evil-4-remake": ["2023", "약 15-30시간", 4, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 93 / Steam 압도적으로 긍정적"],
  "zelda-breath-of-the-wild": ["2017", "약 50-100시간", 3, "싱글플레이", "Switch", "지원", "Metacritic 97 / Steam 없음"],
  "zelda-tears-of-the-kingdom": ["2023", "약 60-120시간", 3, "싱글플레이", "Switch", "지원", "Metacritic 96 / Steam 없음"],
  "dave-the-diver": ["2023", "약 20-35시간", 2, "싱글플레이", "PC, PlayStation, Switch", "지원", "Metacritic 90 / Steam 압도적으로 긍정적"],
  "vampire-survivors": ["2022", "약 20-60시간", 2, "로컬 협동 최대 4명", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 86 / Steam 압도적으로 긍정적"],
  "balatro": ["2024", "약 20-80시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch, Mobile", "미지원", "Metacritic 90 / Steam 압도적으로 긍정적"],
  "valheim": ["2021", "약 60-120시간", 3, "온라인 최대 10명", "PC, Xbox", "지원", "Metacritic 확인 필요 / Steam 압도적으로 긍정적"],
  "palworld": ["2024", "약 40-100시간", 3, "온라인 다인원", "PC, Xbox", "지원", "Metacritic 확인 필요 / Steam 매우 긍정적"],
  "lethal-company": ["2023", "반복 플레이 중심", 3, "온라인 협동 최대 4명", "PC", "미지원", "Metacritic 확인 필요 / Steam 압도적으로 긍정적"],
  "helldivers-2": ["2024", "약 30시간 이상", 4, "온라인 협동 최대 4명", "PC, PlayStation, Xbox", "지원", "Metacritic 82 / Steam 대체로 긍정적"],
  "deep-rock-galactic": ["2020", "약 40시간 이상", 3, "온라인 협동 최대 4명", "PC, PlayStation, Xbox", "지원", "Metacritic 85 / Steam 압도적으로 긍정적"],
  "risk-of-rain-2": ["2020", "약 30-100시간", 4, "온라인 협동 최대 4명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 85 / Steam 압도적으로 긍정적"],
  "no-mans-sky": ["2016", "약 50시간 이상", 3, "온라인 다인원", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 61 / Steam 매우 긍정적"],
  "satisfactory": ["2024", "약 80시간 이상", 3, "온라인 협동", "PC", "지원", "Metacritic 91 / Steam 압도적으로 긍정적"],
  "hi-fi-rush": ["2023", "약 10-15시간", 3, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 90 / Steam 압도적으로 긍정적"],
  "sea-of-stars": ["2023", "약 30-45시간", 2, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 87 / Steam 매우 긍정적"],
  "tunic": ["2022", "약 12-25시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 85 / Steam 매우 긍정적"],
  "undertale": ["2015", "약 6-15시간", 2, "싱글플레이", "PC, PlayStation, Xbox, Switch", "미지원", "Metacritic 92 / Steam 압도적으로 긍정적"],
  "dredge": ["2023", "약 10-20시간", 2, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 85 / Steam 압도적으로 긍정적"],
  "inscryption": ["2021", "약 12-20시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 85 / Steam 압도적으로 긍정적"],
  "cult-of-the-lamb": ["2022", "약 15-35시간", 3, "로컬 협동 2명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 82 / Steam 매우 긍정적"],
  "lies-of-p": ["2023", "약 30-50시간", 5, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 80 / Steam 매우 긍정적"],
  "armored-core-vi": ["2023", "약 20-40시간", 4, "온라인 대전", "PC, PlayStation, Xbox", "지원", "Metacritic 86 / Steam 매우 긍정적"],
  "remnant-2": ["2023", "약 25-60시간", 4, "온라인 협동 최대 3명", "PC, PlayStation, Xbox", "지원", "Metacritic 80 / Steam 매우 긍정적"],
  "phasmophobia": ["2020", "반복 플레이 중심", 3, "온라인 협동 최대 4명", "PC", "지원", "Metacritic 확인 필요 / Steam 압도적으로 긍정적"],
  "project-zomboid": ["2013", "약 50시간 이상", 5, "온라인 다인원", "PC", "지원", "Metacritic 확인 필요 / Steam 매우 긍정적"],
  "binding-of-isaac-rebirth": ["2014", "약 50시간 이상", 4, "로컬 협동 최대 4명", "PC, PlayStation, Xbox, Switch", "미지원", "Metacritic 86 / Steam 압도적으로 긍정적"],
  "euro-truck-simulator-2": ["2012", "약 50시간 이상", 2, "온라인 다인원", "PC", "지원", "Metacritic 79 / Steam 압도적으로 긍정적"],
  "among-us": ["2018", "반복 플레이 중심", 2, "온라인 최대 15명", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 85 / Steam 매우 긍정적"],
  "papers-please": ["2013", "약 5-10시간", 3, "싱글플레이", "PC, PlayStation, Mobile", "지원", "Metacritic 85 / Steam 압도적으로 긍정적"],
  "hotline-miami": ["2012", "약 5-10시간", 4, "싱글플레이", "PC, PlayStation, Switch", "미지원", "Metacritic 85 / Steam 압도적으로 긍정적"],
  "ftl": ["2012", "약 10-40시간", 4, "싱글플레이", "PC, Mobile", "미지원", "Metacritic 84 / Steam 압도적으로 긍정적"],
  "stanley-parable-ultra-deluxe": ["2022", "약 3-8시간", 1, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 90 / Steam 압도적으로 긍정적"],
  "a-short-hike": ["2019", "약 2-5시간", 1, "싱글플레이", "PC, PlayStation, Xbox, Switch", "미지원", "Metacritic 82 / Steam 압도적으로 긍정적"],
  "spiritfarer": ["2020", "약 25-40시간", 2, "로컬 협동 2명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 84 / Steam 압도적으로 긍정적"],
  "inside": ["2016", "약 3-5시간", 2, "싱글플레이", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 87 / Steam 압도적으로 긍정적"],
  "limbo": ["2010", "약 3-5시간", 2, "싱글플레이", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 88 / Steam 압도적으로 긍정적"],
  "fez": ["2013", "약 8-15시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 91 / Steam 매우 긍정적"],
  "spelunky-2": ["2020", "약 20-80시간", 5, "온라인/로컬 협동 최대 4명", "PC, PlayStation, Switch", "지원", "Metacritic 91 / Steam 매우 긍정적"],
  "shovel-knight-treasure-trove": ["2014", "약 20-40시간", 3, "로컬 협동 2명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 85 / Steam 압도적으로 긍정적"],
  "katana-zero": ["2019", "약 5-10시간", 4, "싱글플레이", "PC, Xbox, Switch", "지원", "Metacritic 83 / Steam 압도적으로 긍정적"],
  "hyper-light-drifter": ["2016", "약 8-15시간", 4, "로컬 협동 2명", "PC, PlayStation, Xbox, Switch", "미지원", "Metacritic 84 / Steam 매우 긍정적"],
  "enter-the-gungeon": ["2016", "약 30시간 이상", 4, "로컬 협동 2명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 84 / Steam 압도적으로 긍정적"],
  "darkest-dungeon": ["2016", "약 50시간 이상", 5, "싱글플레이", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 84 / Steam 매우 긍정적"],
  "firewatch": ["2016", "약 4-6시간", 1, "싱글플레이", "PC, PlayStation, Xbox, Switch", "미지원", "Metacritic 81 / Steam 매우 긍정적"],
  "gris": ["2018", "약 3-5시간", 1, "싱글플레이", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 84 / Steam 압도적으로 긍정적"],
  "edith-finch": ["2017", "약 2-3시간", 1, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 89 / Steam 압도적으로 긍정적"],
  "baba-is-you": ["2019", "약 20-40시간", 4, "싱글플레이", "PC, Switch, Mobile", "지원", "Metacritic 87 / Steam 압도적으로 긍정적"],
  "untitled-goose-game": ["2019", "약 3-6시간", 1, "로컬 협동 2명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 79 / Steam 매우 긍정적"],
  "loop-hero": ["2021", "약 20-40시간", 3, "싱글플레이", "PC, Xbox, Switch, Mobile", "지원", "Metacritic 82 / Steam 매우 긍정적"],
  "rain-world": ["2017", "약 20-50시간", 5, "로컬 협동 최대 4명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 66 / Steam 매우 긍정적"],
  "night-in-the-woods": ["2017", "약 8-12시간", 1, "싱글플레이", "PC, PlayStation, Xbox, Switch", "미지원", "Metacritic 88 / Steam 매우 긍정적"],
  "oxenfree": ["2016", "약 4-6시간", 1, "싱글플레이", "PC, PlayStation, Xbox, Switch, Mobile", "미지원", "Metacritic 80 / Steam 매우 긍정적"],
  "crypt-of-the-necrodancer": ["2015", "약 15-40시간", 4, "로컬 협동 2명", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 87 / Steam 압도적으로 긍정적"],
  "superhot": ["2016", "약 3-8시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 82 / Steam 매우 긍정적"],
  "brotato": ["2023", "약 20-60시간", 3, "로컬 협동 최대 4명", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 76 / Steam 압도적으로 긍정적"],
  "unpacking": ["2021", "약 3-5시간", 1, "싱글플레이", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 83 / Steam 압도적으로 긍정적"],
  "dorfromantik": ["2022", "약 10-30시간", 2, "싱글플레이", "PC, Switch", "지원", "Metacritic 80 / Steam 압도적으로 긍정적"],
  "mini-motorways": ["2021", "약 10-30시간", 3, "싱글플레이", "PC, PlayStation, Switch, Mobile", "지원", "Metacritic 87 / Steam 매우 긍정적"],
  "half-life-2": ["2004", "약 12-15시간", 3, "싱글플레이", "PC", "지원", "Metacritic 96 / Steam 압도적으로 긍정적"],
  "portal": ["2007", "약 3-4시간", 2, "싱글플레이", "PC", "지원", "Metacritic 90 / Steam 압도적으로 긍정적"],
  "counter-strike-2": ["2023", "제한없음", 4, "온라인 대전", "PC", "지원", "Metacritic 확인 필요 / Steam 매우 긍정적"],
  "gta-5": ["2015", "약 30-100시간", 3, "싱글플레이 및 온라인 다인원", "PC, PlayStation, Xbox", "지원", "Metacritic 확인 필요 / Steam 매우 긍정적"],
  "skyrim": ["2011", "약 100시간 이상", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "미지원", "Metacritic 94 / Steam 압도적으로 긍정적"],
  "fallout-4": ["2015", "약 80-150시간", 3, "싱글플레이", "PC, PlayStation, Xbox", "미지원", "Metacritic 84 / Steam 매우 긍정적"],
  "bioshock-infinite": ["2013", "약 12시간", 3, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 94 / Steam 압도적으로 긍정적"],
  "dishonored-2": ["2016", "약 15-20시간", 4, "싱글플레이", "PC, PlayStation, Xbox", "미지원", "Metacritic 86 / Steam 매우 긍정적"],
  "doom-eternal": ["2020", "약 20시간", 4, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 88 / Steam 압도적으로 긍정적"],
  "control": ["2019", "약 12-20시간", 3, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 85 / Steam 매우 긍정적"],
  "resident-evil-village": ["2021", "약 10-12시간", 4, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 83 / Steam 매우 긍정적"],
  "death-stranding": ["2022", "약 40-60시간", 3, "싱글플레이", "PC, PlayStation", "지원", "Metacritic 85 / Steam 매우 긍정적"],
  "hogwarts-legacy": ["2023", "약 35-50시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 83 / Steam 매우 긍정적"],
  "starfield": ["2023", "약 40-100시간", 3, "싱글플레이", "PC, Xbox", "미지원", "Metacritic 87 / Steam 복합적"],
  "diablo-4": ["2023", "약 30시간 이상", 4, "온라인 협동 최대 4명", "PC, PlayStation, Xbox", "지원", "Metacritic 88 / Steam 복합적"],
  "path-of-exile": ["2013", "제한없음", 5, "온라인 협동 다인원", "PC, PlayStation, Xbox", "지원", "Metacritic 86 / Steam 매우 긍정적"],
  "warframe": ["2013", "제한없음", 4, "온라인 협동 최대 4명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 69 / Steam 매우 긍정적"],
  "apex-legends": ["2020", "제한없음", 4, "온라인 3인 스쿼드 대전", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 88 / Steam 매우 긍정적"],
  "rust": ["2018", "제한없음", 5, "온라인 다인원", "PC, PlayStation, Xbox", "지원", "Metacritic 69 / Steam 매우 긍정적"],
  "ark-survival-evolved": ["2017", "약 60시간 이상", 4, "온라인 다인원", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 70 / Steam 복합적"],
  "sons-of-the-forest": ["2024", "약 15-25시간", 4, "온라인 협동 최대 8명", "PC, PlayStation", "지원", "Metacritic 86 / Steam 매우 긍정적"],
  "v-rising": ["2024", "약 30-50시간", 4, "온라인 협동 및 대전", "PC, PlayStation, Xbox", "지원", "Metacritic 85 / Steam 매우 긍정적"],
  "dying-light-2": ["2022", "약 20-30시간", 3, "온라인 협동 최대 4명", "PC, PlayStation, Xbox", "지원", "Metacritic 77 / Steam 대체로 긍정적"],
  "left-4-dead-2": ["2009", "약 10-15시간", 3, "온라인 협동 최대 4명", "PC", "지원", "Metacritic 89 / Steam 압도적으로 긍정적"],
  "team-fortress-2": ["2007", "제한없음", 3, "온라인 대전", "PC", "지원", "Metacritic 92 / Steam 압도적으로 긍정적"],
  "monster-hunter-rise": ["2022", "약 40-80시간", 4, "온라인 협동 최대 4명", "PC, Switch, PlayStation, Xbox", "지원", "Metacritic 86 / Steam 매우 긍정적"],
  "street-fighter-6": ["2023", "제한없음", 4, "온라인 대전", "PC, PlayStation, Xbox", "지원", "Metacritic 92 / Steam 매우 긍정적"],
  "tekken-8": ["2024", "제한없음", 4, "온라인 대전", "PC, PlayStation, Xbox", "지원", "Metacritic 91 / Steam 매우 긍정적"],
  "rocket-league": ["2015", "제한없음", 3, "온라인 대전 및 협동", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 86 / Steam 매우 긍정적"],
  "human-fall-flat": ["2016", "약 5-8시간", 1, "온라인 협동 최대 8명", "PC, PlayStation, Xbox, Switch, Mobile", "지원", "Metacritic 70 / Steam 매우 긍정적"],
  "overcooked-2": ["2018", "약 10시간", 3, "온라인 협동 최대 4명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 81 / Steam 매우 긍정적"],
  "hunt-showdown": ["2019", "제한없음", 5, "온라인 협동/대전 최대 3인 팀", "PC, PlayStation, Xbox", "지원", "Metacritic 81 / Steam 매우 긍정적"],
  "metro-exodus": ["2019", "약 15시간", 3, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 85 / Steam 매우 긍정적"],
  "titanfall-2": ["2016", "약 6-8시간", 3, "싱글플레이 및 온라인 대전", "PC, PlayStation, Xbox", "미지원", "Metacritic 86 / Steam 압도적으로 긍정적"],
  "borderlands-3": ["2019", "약 30-35시간", 3, "온라인 협동 최대 4명", "PC, PlayStation, Xbox", "지원", "Metacritic 81 / Steam 대체로 긍정적"],
  "deltarune": ["2025", "약 15-20시간", 2, "싱글플레이", "PC, PlayStation, Xbox, Switch", "미지원", "Metacritic 86 / Steam 압도적으로 긍정적"],
  "cocoon": ["2023", "약 5-6시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 88 / Steam 매우 긍정적"],
  "chicory": ["2021", "약 15-20시간", 2, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 90 / Steam 압도적으로 긍정적"],
  "neon-white": ["2022", "약 6-8시간", 4, "싱글플레이", "PC, Switch", "지원", "Metacritic 89 / Steam 압도적으로 긍정적"],
  "pizza-tower": ["2023", "약 8-10시간", 4, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 89 / Steam 압도적으로 긍정적"],
  "signalis": ["2022", "약 8-10시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 81 / Steam 매우 긍정적"],
  "pentiment": ["2022", "약 15-20시간", 2, "싱글플레이", "PC, Xbox", "지원", "Metacritic 88 / Steam 매우 긍정적"],
  "astroneer": ["2019", "약 15-25시간", 2, "온라인 협동 다인원", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 71 / Steam 매우 긍정적"],
  "core-keeper": ["2024", "약 30-50시간", 3, "온라인 협동 최대 8명", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 86 / Steam 매우 긍정적"],
  "raft": ["2022", "약 20-30시간", 2, "온라인 협동 다인원", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 확인 필요 / Steam 매우 긍정적"],
  "a-plague-tale-requiem": ["2022", "약 15시간", 3, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 82 / Steam 매우 긍정적"],
  "little-nightmares-2": ["2021", "약 6-8시간", 3, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 83 / Steam 매우 긍정적"],
  "kena-bridge-of-spirits": ["2021", "약 12-15시간", 3, "싱글플레이", "PC, PlayStation", "지원", "Metacritic 83 / Steam 매우 긍정적"],
  "against-the-storm": ["2023", "약 30시간 이상", 4, "싱글플레이", "PC", "지원", "Metacritic 91 / Steam 압도적으로 긍정적"],
  "terra-nil": ["2023", "약 5-8시간", 2, "싱글플레이", "PC, PlayStation, Xbox, Switch", "지원", "Metacritic 79 / Steam 매우 긍정적"],
  "wukong": ["2024", "약 25-35시간", 4, "싱글플레이", "PC, PlayStation, Xbox", "지원", "Metacritic 82 / Steam 매우 긍정적"]
};

const gameCoverAppIds = {
  "elden-ring": 1245620,
  "dark-souls-3": 374320,
  "the-witcher-3": 292030,
  "baldurs-gate-3": 1086940,
  "stardew-valley": 413150,
  "terraria": 105600,
  "hades": 1145360,
  "dead-cells": 588650,
  "civilization-vi": 289070,
  "xcom-2": 268500,
  "portal-2": 620,
  "the-witness": 210970,
  "hollow-knight": 367520,
  "ori-will-of-the-wisps": 1057090,
  "celeste": 504230,
  "slay-the-spire": 646570,
  "subnautica": 264710,
  "dont-starve": 219740,
  "mass-effect-2": 2362420,
  "it-takes-two": 1426210,
  "cyberpunk-2077": 1091500,
  "red-dead-redemption-2": 1174180,
  "god-of-war": 1593500,
  "horizon-zero-dawn": 1151640,
  "ghost-of-tsushima": 2215430,
  "monster-hunter-world": 582010,
  "sekiro": 814380,
  "nioh-2": 1325200,
  "persona-5-royal": 1687950,
  "dragon-quest-xi-s": 1295510,
  "final-fantasy-vii-remake": 1462040,
  "nier-automata": 524220,
  "disco-elysium": 632470,
  "divinity-original-sin-2": 435150,
  "rimworld": 294100,
  "factorio": 427520,
  "oxygen-not-included": 457140,
  "cities-skylines": 255710,
  "the-sims-4": 1222670,
  "into-the-breach": 590380,
  "total-war-three-kingdoms": 779340,
  "age-of-empires-ii-de": 813780,
  "tetris-effect-connected": 1003590,
  "return-of-the-obra-dinn": 653530,
  "outer-wilds": 753640,
  "cuphead": 268910,
  "the-last-of-us-part-ii": 2531310,
  "uncharted-4": 1659420,
  "resident-evil-4-remake": 2050650,
  "dave-the-diver": 1868140,
  "vampire-survivors": 1794680,
  "balatro": 2379780,
  "valheim": 892970,
  "palworld": 1623730,
  "lethal-company": 1966720,
  "helldivers-2": 553850,
  "deep-rock-galactic": 548430,
  "risk-of-rain-2": 632360,
  "no-mans-sky": 275850,
  "satisfactory": 526870,
  "hi-fi-rush": 1817230,
  "sea-of-stars": 1244090,
  "tunic": 553420,
  "undertale": 391540,
  "dredge": 1562430,
  "inscryption": 1092790,
  "cult-of-the-lamb": 1313140,
  "lies-of-p": 1627720,
  "armored-core-vi": 1888160,
  "remnant-2": 1282100,
  "phasmophobia": 739630,
  "project-zomboid": 108600,
  "binding-of-isaac-rebirth": 250900,
  "euro-truck-simulator-2": 227300,
  "among-us": 945360,
  "papers-please": 239030,
  "hotline-miami": 219150,
  "ftl": 212680,
  "stanley-parable-ultra-deluxe": 1703340,
  "a-short-hike": 1055540,
  "spiritfarer": 972660,
  "inside": 304430,
  "limbo": 48000,
  "fez": 224760,
  "spelunky-2": 418530,
  "shovel-knight-treasure-trove": 250760,
  "katana-zero": 460950,
  "hyper-light-drifter": 257850,
  "enter-the-gungeon": 311690,
  "darkest-dungeon": 262060,
  "firewatch": 383870,
  "gris": 683320,
  "edith-finch": 501300,
  "baba-is-you": 736260,
  "untitled-goose-game": 837470,
  "loop-hero": 1282730,
  "rain-world": 312520,
  "night-in-the-woods": 481510,
  "oxenfree": 388880,
  "crypt-of-the-necrodancer": 247080,
  "superhot": 322500,
  "brotato": 1942280,
  "unpacking": 1135690,
  "dorfromantik": 1455840,
  "mini-motorways": 1127500,
  "half-life-2": 220,
  "portal": 400,
  "counter-strike-2": 730,
  "gta-5": 3240220,
  "skyrim": 489830,
  "fallout-4": 377160,
  "bioshock-infinite": 8870,
  "dishonored-2": 403640,
  "doom-eternal": 782330,
  "control": 870780,
  "resident-evil-village": 1196590,
  "death-stranding": 1850570,
  "hogwarts-legacy": 990080,
  "starfield": 1716740,
  "diablo-4": 2344520,
  "path-of-exile": 238960,
  "warframe": 230410,
  "apex-legends": 1172470,
  "rust": 252490,
  "ark-survival-evolved": 346110,
  "sons-of-the-forest": 1326470,
  "v-rising": 1604030,
  "dying-light-2": 534380,
  "left-4-dead-2": 550,
  "team-fortress-2": 440,
  "monster-hunter-rise": 1446780,
  "street-fighter-6": 1364780,
  "tekken-8": 1778820,
  "rocket-league": 252950,
  "human-fall-flat": 477160,
  "overcooked-2": 728880,
  "hunt-showdown": 594650,
  "metro-exodus": 412020,
  "titanfall-2": 1237970,
  "borderlands-3": 397540,
  "deltarune": 1671210,
  "cocoon": 1497440,
  "chicory": 1123450,
  "neon-white": 1533420,
  "pizza-tower": 2231450,
  "signalis": 1262350,
  "pentiment": 1205520,
  "astroneer": 361420,
  "core-keeper": 1621690,
  "raft": 648800,
  "a-plague-tale-requiem": 1182900,
  "little-nightmares-2": 860510,
  "kena-bridge-of-spirits": 1954200,
  "against-the-storm": 1336490,
  "terra-nil": 1593030,
  "wukong": 2358720
};

const gameCoverUrls = {
  "animal-crossing": "https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/store/software/switch/70010000027619/9989957eae3a6b545194c42fec2071675c34aadacd65e6b33fdfe7b3b6a86c3a",
  "bloodborne": "https://image.api.playstation.com/cdn/UP9000/CUSA00900_00/9EJsLXyKS0S1BRey5nwQBOuYr6EDRbGX.png",
  "fire-emblem-three-houses": "https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/store/software/switch/70010000007606/c499fdc86779ca95e61daed1f94288a245d196360d278138e56d44097d1a3878",
  "super-mario-odyssey": "https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/store/software/switch/70010000001130/c42553b4fd0312c31e70ec7468c6c9bccd739f340152925b9600631f2d29f8b5",
  "metroid-dread": "https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/store/software/switch/70010000042924/4f2c683f0196210ec212a2ab8bf6952223c0b88e827b820953407a2ba61c9cb2",
  "zelda-breath-of-the-wild": "https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/store/software/switch/70010000000025/7137262b5a64d921e193653f8aa0b722925abc5680380ca0e18a5cfd91697f58",
  "zelda-tears-of-the-kingdom": "https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/store/software/switch/70010000063714/fb30eab428df3fc993b41c76e20f72e4d76d49734d17d31996b5ab61c414b117"
};

const gameCoverLocalFiles = {
  "minecraft": "minecraft.jpg"
};

const gameCoverFocus = {
  "animal-crossing": "68%",
  "minecraft": "52%",
  "zelda-breath-of-the-wild": "30%",
  "zelda-tears-of-the-kingdom": "73%"
};
